<?php /* @var Pinterest\PinterestMagento2Extension\Block\Tag\Checkout $block */ ?>
<?php
$storeId = $block->getCurrentStoreId();
if ($block->isTagEnabled($storeId)) {
    $eventId = Pinterest\PinterestMagento2Extension\Helper\EventIdGenerator::guidv4();
    $productDetails = $block->getProductDetails();
    $currency = $block->getCurrency();
    $block->trackCheckoutEvent($eventId, $productDetails, $currency, $storeId);
    ?>
    <!-- Pinterest Checkout Tag Code -->
    <script>
        pintrk('track', 'checkout', {
            event_id: "<?= $escaper->escapeJs($eventId) ?>",
            order_quantity: <?= $escaper->escapeJs($productDetails["num_items"]) ?>,
            currency: "<?= $escaper->escapeJs($currency) ?>",
            value: <?= $escaper->escapeJs($productDetails["value"]) ?>,
            order_id: "<?= $escaper->escapeJs($productDetails["order_id"]) ?>",
            line_items: <?= /* @noEscape */ json_encode($productDetails["line_tems"]) ?>
        });
    </script>
    <!-- End of Pinterest Checkout Tag Code -->
<?php } ?>