<?php /* @var Pinterest\PinterestMagento2Extension\Block\Tag\Checkout $block */ ?>
<?php if ($block->isTagEnabled()) {
    $eventId = Pinterest\PinterestMagento2Extension\Helper\EventIdGenerator::guidv4();
    $productDetails = $block->getProductDetails();
    $currency = $block->getCurrency();
    $block->trackCheckoutEvent($eventId, $productDetails, $currency);
    ?>
    <!-- Pinterest Checkout Tag Code -->
    <script>
        pintrk('track', 'checkout', {
            event_id: "<?= $eventId ?>",
            order_quantity: <?= $productDetails["num_items"] ?>,
            currency: "<?= $currency ?>",
            value: <?= $productDetails["value"] ?>,
            order_id: "<?= $productDetails["order_id"] ?>",
            line_items: <?= json_encode($productDetails["line_tems"]) ?>
        });
    </script>
    <!-- End of Pinterest Checkout Tag Code -->
<?php } ?>