<?php /** @var Pinterest\PinterestMagento2Extension\Block\Adminhtml\Setup $block */ ?>
<?php if ($block->isTagEnabled()) { ?>
    <!-- Pinterest HTML Tag -->
    <?= $block->getMetaTag() ?>
    <!-- End of Pinterest HTML Tag -->
    <!-- Pinterest Pixel Base Code -->
    <script type="text/javascript">
        !function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(
            Array.prototype.slice.call(arguments))};var
            n=window.pintrk;n.queue=[],n.version="3.0";var
            t=document.createElement("script");t.async=!0,t.src=e;var
            r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");
        window.pintrk.partnerData={"np":"adobe"};
        pintrk('setconsent', <?= $block->isUserOptedOutOfTracking() ? "false" : "true" ?>);
        pintrk("load", "<?= $block->getTagId() ?>", {
            <?php if ($block->getHashedEmailId()) { ?>
                "em": "<?= $block->getHashedEmailId() ?>"
            <?php } ?>
        });
        pintrk("page");
    </script>
    <!-- End Pinterest Pixel Base Code -->
<?php } ?>
