<?php /** @var Pinterest\PinterestMagento2Extension\Block\Adminhtml\Setup $block */ ?>
<?php
$storeId = $block->getCurrentStoreId();
if ($block->isUserConnected($storeId)) { ?>
    <!-- Pinterest HTML Tag -->
    <?= /* @noEscape */ $block->getMetaTag($storeId) ?>
    <!-- End of Pinterest HTML Tag -->
    <?php if ($block->isTagEnabled($storeId)) { ?>
        <!-- Pinterest Pixel Base Code -->
        <script type="text/javascript">
            !function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(
                Array.prototype.slice.call(arguments))};var
                n=window.pintrk;n.queue=[],n.version="3.0";var
                t=document.createElement("script");t.async=!0,t.src=e;var
                r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");
            window.pintrk.partnerData={"np":"adobe"};
            <?php if ($block->isLdpEnabled($storeId)) { ?>
                var state = "<?= $escaper->escapeJs($block->getHashedState())?>";
                var country = "<?= $escaper->escapeJs($block->getHashedCountry())?>";
                pintrk('set', {
                    opt_out_type: 'LDP',
                    st: state,
                    country: country,
                });
            <?php } ?>
            var setCMSConsentCookie = function(value) {
                document.cookie = "PinterestMagento2ExtensionConsentCookie=" + JSON.stringify({consent: value}) + ";path=/";
            }
            var cmsCookieCallback = function(e) {
                if (Cookiebot && Cookiebot.consent && Cookiebot.consent.marketing) {
                    setCMSConsentCookie(true);
                    pintrk('setconsent', true);
                } else {
                    setCMSConsentCookie(false);
                    pintrk('setconsent', false);
                }
            }
            pintrk('setconsent', function() {
                    // Keep in sync with PinterestHelper::isUserOptedOutOfTracking
                    var config = {
                        "isCookieRestrictionModeEnabled": <?= /* @noEscape */ $block->isCookieRestrictionModeEnabled() ?>,
                        "currentWebsite": <?= /* @noEscape */ $block->getCurrentWebsiteId() ?>,
                        "cookieName": "<?= /* @noEscape */ $block->getGDPRCookieName($storeId) ?>",
                        "isGdprEnabled": <?= /* @noEscape */ $block->isGdprEnabled($storeId) ?>,
                        "gdprOption": <?= /* @noEscape */ $block->getGdprOption($storeId) ?>
                    }
                    var getCookie = function(name) {
                        var value = `; ${document.cookie}`;
                        var parts = value.split(`; ${name}=`);
                        if (parts.length === 2) return parts.pop().split(';').shift();
                    }
                    if (!config.isGdprEnabled) {
                        return true;
                    } else if (config.isCookieRestrictionModeEnabled && config.gdprOption === 1) {
                        var cookieValue = getCookie(config.cookieName);
                        if (cookieValue) {
                            gdprCookie = unescape(cookieValue);
                            if (gdprCookie) {
                                gdprCookieObj = JSON.parse(gdprCookie);
                                return gdprCookieObj[config.currentWebsite] === 1;
                            }
                        }
                        return false;
                    } else if (config.gdprOption === 2) {
                        return !!(getCookie(config.cookieName)) && getCookie(config.cookieName) !== "0";
                    } else if (config.gdprOption === 3) {
                        window.addEventListener('CookiebotOnConsentReady', cmsCookieCallback);
                        window.addEventListener('CookiebotOnLoad', cmsCookieCallback);
                        cookieValue = getCookie('PinterestMagento2ExtensionConsentCookie');
                        if (cookieValue) {
                            gdprCookieObj = JSON.parse(unescape(cookieValue));
                            if(gdprCookieObj.consent) {
                                return true;
                            }
                        } else if (Cookiebot && Cookiebot.consent && Cookiebot.consent.marketing) {
                            setCMSConsentCookie(true);
                            return true;
                        }
                        return false;
                    }
                    return true;
                }());
            pintrk("load", "<?= /* @noEscape */ $block->getTagId($storeId) ?>", {
                    <?php if ($block->getHashedEmailId()) { ?>
                        "em": "<?= /* @noEscape */ $block->getHashedEmailId() ?>"
                    <?php } ?>
            });
            pintrk("page");
        <?php } ?>
    </script>
    <!-- End Pinterest Pixel Base Code -->
<?php } ?>
