<?php /* @var Pinterest\PinterestMagento2Extension\Block\Adminhtml\Setup $block */ ?>
<?php
$storeId = $block->getCurrentStoreId();
if ($block->isTagEnabled($storeId)) {
    $productDetails = $block->getProductDetails();
    $currency = $block->getCurrency();
    ?>
    <!-- Pinterest Page Visit Tag Code -->
    <script>
        require([
            "jquery",
            "jquery/jquery.cookie"
        ], function ($) {
            var conversionEventUrl = "<?= /* @noEscape */ $block->getConversionEventUrl() ?>";
            $(document).ready(function () {
                let ajaxData = {storeId: "<?= $storeId ?>"};
                let pintrkData = {};
            <?php if (!empty($productDetails)) { ?>
                    var productData = {
                        product_id: "<?= $escaper->escapeJs($productDetails["product_id"])  ?>",
                        product_price: <?= $productDetails["product_price"] ?>,
                        product_name: "<?= $escaper->escapeJs($productDetails["product_name"]) ?>",
                        product_quantity: 1,
                        product_category: <?= json_encode($productDetails["product_category"]) ?>
                    }
                    ajaxData = {
                            productData,
                            order_quantity: 0,
                            currency: "<?= $currency ?>",
                            storeId: "<?= $storeId ?>"
                        }
                    pintrkData = {
                        line_items: [productData],
                        order_quantity: 0,
                        currency: "<?= $currency ?>"
                    }
                <?php } ?>

                $.ajax({
                    url: conversionEventUrl,
                    data: {
                        event_name: 'page_visit',
                        data: ajaxData
                    },
                    type: "post",
                    dataType: "json",
                    success: function (res) {
                        if (res.event_id) {
                            pintrk('track', 'pagevisit', {
                                event_id: res.event_id,
                                ...pintrkData
                            });
                        }
                    }
                });
            });
        });
    </script>
    <!-- End of Pinterest Page Visit Tag Code -->
<?php } ?>