<?php /* @var Pinterest\PinterestMagento2Extension\Block\Tag\Search $block */ ?>
<?php if ($block->isTagEnabled()) {
    $search_query = $block->getSearchQuery();
    ?>
    <!-- Pinterest Tag Search Code -->
    <script>
        require([
            "jquery",
            "jquery/jquery.cookie"
        ], function ($) {
            var conversionEventUrl = "<?= /* @noEscape */ $block->getConversionEventUrl() ?>";
            $(document).ready(function () {
                var search_query = "<?= $search_query ?>"
                $.ajax({
                    url: conversionEventUrl,
                    data: {
                        event_name: 'search',
                        data: {
                            search_query
                        }
                    },
                    type: "post",
                    dataType: "json",
                    success: function (res) {
                        if (res.event_id) {
                            pintrk('track', 'search', {
                                event_id: res.event_id,
                                search_query
                            });
                        }
                    }
                });
            });
        });

    </script>
    <!-- End of Pinterest Tag Search Code -->
<?php } ?>