<?php if ($block->isTagEnabled()) {
    $eventId = Pinterest\PinterestMagento2Extension\Helper\EventIdGenerator::guidv4();
    $productDetails = $block->getAllProductDetails();
    $currency = $block->getCurrency();
    ?>
    <!-- Pinterest Pinterest View Category Tag Code -->
    <script>
        require([
            "jquery"
        ], function ($) {
            var conversionEventUrl = "<?= /* @noEscape */ $block->getConversionEventUrl() ?>";
            $(document).ready(function () {
                let ajaxData = {};
                let pintrkData = {};
                <?php if (!empty($productDetails)) { ?>
                    ajaxData = {
                        productDetails: <?= json_encode($productDetails) ?>,
                        currency: "<?= $currency ?>"
                    }
                    pintrkData = {
                        line_items: <?= json_encode($productDetails["line_tems"]) ?>,
                        currency: "<?= $currency ?>"
                    }
                <?php } ?>

                $.ajax({
                    url: conversionEventUrl,
                    data: {
                        event_name: 'view_category',
                        data: ajaxData
                    },
                    type: "post",
                    dataType: "json",
                    success: function (res) {
                        if (res.event_id) {
                            pintrk('track', 'viewcategory', {
                                event_id: res.event_id,
                                ...pintrkData
                            });
                        }
                    }
                });
            });
        });
    </script>
    <!-- End of Pinterest View Category Tag Code -->
<?php } ?>