<?php
$storeId = $block->getCurrentStoreId();
if ($block->isTagEnabled($storeId)) {
    $eventId = Pinterest\PinterestMagento2Extension\Helper\EventIdGenerator::guidv4();
    $productDetails = $block->getAllProductDetails();
    $currency = $block->getCurrency();
    ?>
    <!-- Pinterest Pinterest View Category Tag Code -->
    <script>
        require([
            "jquery"
        ], function ($) {
            var conversionEventUrl = "<?= /* @noEscape */ $block->getConversionEventUrl() ?>";
            $(document).ready(function () {
                let ajaxData = {storeId: "<?= $escaper->escapeJs($storeId) ?>"};
                let pintrkData = {};
                <?php if (!empty($productDetails)) { ?>
                    ajaxData = {
                        productDetails: <?= /* @noEscape */ json_encode($productDetails) ?>,
                        currency: "<?= $escaper->escapeJs($currency) ?>",
                        storeId: "<?= $escaper->escapeJs($storeId) ?>"
                    }
                    pintrkData = {
                        line_items: <?= /* @noEscape */ json_encode($productDetails["line_tems"]) ?>,
                        currency: "<?= $escaper->escapeJs($currency) ?>"
                    }
                <?php } ?>

                $.ajax({
                    url: conversionEventUrl,
                    data: {
                        event_name: 'view_category',
                        data: ajaxData
                    },
                    type: "post",
                    dataType: "json",
                    success: function (res) {
                        if (res.event_id) {
                            pintrk('track', 'viewcategory', {
                                event_id: res.event_id,
                                ...pintrkData
                            });
                        }
                    }
                });
            });
        });
    </script>
    <!-- End of Pinterest View Category Tag Code -->
<?php } ?>