<?php /** @var Pinterest\PinterestMagento2Extension\Block\Adminhtml\Setup $block */
$config = $block->scriptConfigAfterConnect()
?>
<div>
    <script type="text/javascript">
        require(['app_script'], function(initScript) {
            const SETTINGS_PAGE = "<?= $config['pinterestBaseUrl'] ?>/business/commerce-integrations/apps/<?= $config['iframeVersion'] ?>/settings/<?= $config['locale'] ? "?locale=".$config['locale'] : "" ?>";
            initScript(<?php print(json_encode($config, JSON_UNESCAPED_SLASHES)) ?>, SETTINGS_PAGE);
        });
    </script>
    <iframe id="pinterest-iframe" width="700px" height="1200px" frameBorder="0"></iframe>
</div>
