<?php /* @var $block \Pinterest\PinterestMagento2Extension\Block\Adminhtml\System\Config\RegisterCatalogFeeds */ ?>
<script>
    require([
        'jquery',
        'prototype',
    ], function ($) {
        function registerAllFeeds() {
            params = {};
            var generalError = `<?= $escaper->escapeHtml(__('There was an issue regenerating your catalog. Please refresh the page or trying again later.')) ?>`;
            new Ajax.Request('<?= /* @noEscape */ $block->getAjaxUrl() ?>', {
                loaderArea: false,
                asynchronous: true,
                parameters: params,
                onSuccess: function (transport) {
                    var response = JSON.parse(transport.responseText);
                    if (response && response.success) {
                        $('#messages .message-success span.message-text').text(`<?= $escaper->escapeHtml(__("Success")) ?>`);
                        $('#messages .message-success').show();
                        $('#messages .message-success').delay(8000).fadeOut();
                    } else {
                        var errorMessage = response && response.user_logged_out ? 
                            `<?= $escaper->escapeHtml(__('You must be logged into Pinterest to access this setting')) ?>` : 
                            generalError
                        $('#messages .message-error span.message-text').text(errorMessage);
                        $('#messages .message-error').show();
                        $('#messages .message-error').delay(8000).fadeOut();
                    return false;
                    }

                },
                onFailure: function() {               
                    $('#messages .message-error span.message-text').text(generalError);
                    $('#messages .message-error').show();
                    $('#messages .message-error').delay(8000).fadeOut();
                    return false;
                }
            });
        }
        $('#pin_catalog_sync_btn').click(function () {
            registerAllFeeds();
        });
    });
</script>


<?= $block->getButtonHtml() ?>
<div id="messages" >
    <div class="messages">
        <div class="message message-success success" style="display: none;">
            <div data-ui-id="messages-message-success">
                <span class="message-text"></span>
            </div>
        </div>
        <div class="message message-error error" style="display: none;">
            <div data-ui-id="messages-message-error">
                <span class="message-text"></span>
            </div>
        </div>
    </div>
</div>
