<?php /** @var Pinterest\PinterestMagento2Extension\Block\Adminhtml\Setup $block */
$config = $block->scriptConfigBeforeConnect()
?>
<div>
    <script type="text/javascript">
        require(['setup_script'], function(initScript) {
            const SETUP_PAGE = "<?= $escaper->escapeJs($config['pinterestBaseUrl']) ?>/business/commerce-integrations/apps/<?= $escaper->escapeJs($config['iframeVersion']) ?>/connect/<?= $escaper->escapeJs($config['locale'] ? "?locale=".$config['locale'] : "") ?>";
            initScript(<?= /* @noEscape */ json_encode($config, JSON_UNESCAPED_SLASHES) ?>, SETUP_PAGE, <?= /* @noEscape */ json_encode($block->getWebsites()) ?>, <?= /* @noEscape */ json_encode($block->getConnectedStoreIds()) ?>);
        });
    </script>
    <iframe id="pinterest-iframe" onload="this.width=screen.width;this.height=screen.height;" frameBorder="0"></iframe>
</div>